### ISSUE TITLE
About dataset mentioned in the article

### ISSUE THREAD

**Issue by lvzhiqiang** [yifan16/av-spk-diarization#1]
I couldn't find the large scale dataset "A large-scale audio-visual corpus for multimodal speaker diarization, speech separation and recognition" mentioned in the article. Even the dataset article could not be found. What happened to the dataset? Where could I download the dataset article and the dataset? 
Thank you a lot!

**Comment by yifan16** [comment]
Hi there,

Thanks for your interest in our paper. Unfortunately, the dataset was collected and copyrighted by the company. When I submitted the paper they planned to release the dataset soon. And I don’t know weather the plan was changed after I left the company. FYI.

Best,
Yifan

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: lvzhiqiang ***@***.***>
Sent: Friday, June 17, 2022 3:40:17 AM
To: yifan16/av-spk-diarization ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [yifan16/av-spk-diarization] About dataset mentioned in the article (Issue #1)


I couldn't find the large scale dataset "A large-scale audio-visual corpus for multimodal speaker diarization, speech separation and recognition" mentioned in the article. Even the dataset article could not be found. What happened to the dataset? Where could I download the dataset article and the dataset?
Thank you a lot!
